test = {   'name': 'q26',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> round(float(small_stats[0]), 2) == 26.32\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> round(float(small_stats[1]), 2) == 4283910.89\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> round(float(large_stats[0]), 2) == 26.42\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> round(float(large_stats[1]), 2) == 4821322.5\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
