test = {   'name': 'q33',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> seconds_in_an_hour != 60 # oops! the number of seconds in an hour is not quite that. it is somewhere between 59 and 61...\nFalse',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> seconds_in_an_hour == 60\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
